FROM public.ecr.aws/docker/library/golang:1.24.5-alpine AS builder

RUN apk update && apk upgrade && \
    apk --update add git make bash build-base

ENV GO111MODULE=on
ENV CGO_ENABLED=1

WORKDIR /app

RUN go install github.com/air-verse/air@latest

COPY . .

RUN go mod download

CMD ["air"]
